# Generated by Django 2.2.4 on 2019-11-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0002_auto_20191015_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasRecursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.DateField(blank=True, null=True)),
                ('informacion_recurso', models.DateField(blank=True, null=True)),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistentes.TemasRecursos')),
            ],
        ),
    ]
