# Generated by Django 2.2.4 on 2019-11-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0003_recursos_temasrecursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='informacion_recurso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='temasrecursos',
            name='nombre_tema',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
