# Generated by Django 3.0.2 on 2020-01-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0004_auto_20191110_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='rol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
