# Generated by Django 3.0.2 on 2020-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0007_auto_20200119_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='rol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
